test:
  script:
    # Setup virtualenv.
    - python3.8 -m venv spins-env
    - source spins-env/bin/activate
    # Install spins.
    - pip3 install .[test]
    - export MPLBACKEND=agg
    - export OPENBLAS_NUM_THREADS=1
    - python -m pytest -n 4 examples --disable-warnings
    - python -m pytest -n 4 --cov=spins --disable-warnings
