language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  # Update installed packages.
  - pip install -U numpy pytest
  - pip install .[test]
  - pip install codecov pytest-cov
script:
  - MPLBACKEND=Agg python -m pytest -n 4 examples --disable-warnings
  - MPLBACKEND=Agg python -m pytest -n 4 --cov=spins --disable-warnings
  - codecov
